export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';  

export const REQUEST_ROBOTS_PRENDING = 'REQUEST_ROBOTS_PRENDING';
export const REQUEST_ROBOTS_SUCCESS = 'REQUEST_ROBOTS_SUCCESSS';
export const REQUEST_ROBOTS_FAILED = 'REQUEST_ROBOTS_FAILED';
